### ISSUE TITLE
Exploración Inicial

### ISSUE THREAD

**Issue by laural87** [laural87/proyecto_visualizacion_vizlab#1]
- [x] Conocer los datos
- [x] Identificar nulos y decidir cómo gestionarlos
- [x] Identificar las transformaciones de datos necesarias
- [x] Identificar datos redundantes que deban ser eliminados
- [x] Crear visualizaciones para explorar

**Comment by carla-caracola** [comment]
Chicas, dejo por acá el link a las conclusiones a las que llegamos: [Conclusiones EDA](https://docs.google.com/document/d/1EyN2ToXDAKecXflh1zreG0ezoZ1gWBvBNFjZpEtYXtw/edit).- Resalté en un mismo color, aquellas a las que creo que que debería tomar la misma persona por estar relacionadas. Es una sugerencia que podemos reveer si queda muy desbalanceada.
