### ISSUE TITLE
Automatización del proceso de extracción y transformación

### ISSUE THREAD

**Issue by laural87** [laural87/proyecto_visualizacion_vizlab#4]
-  Proceso extracción y transformación automatizados. 
- Pasar a .py

**Comment by carla-caracola** [comment]
Update del día: tenemos la automatización casi terminada. Quedan pendiente las siguientes columnas: 

- [ ] market_segment --> Se encargará Carmen
- [ ] reservation_status_date --> Se encargará Carla
