### ISSUE TITLE
Definir visualizaciones/historias

### ISSUE THREAD

**Issue by laural87** [laural87/proyecto_visualizacion_vizlab#6]
- [ ] Definir objetivo/s y preguntas a responder
- [ ] Identificar a la audiencia
- [ ] Definir tipos de gráficos y datos a mostrar

**Comment by carla-caracola** [comment]
Documento "[Búsqueda de patrones](https://docs.google.com/document/d/1yFFq6WwbvQlE5-8n-A6peDeib8CbVe3frB3jOJ8SeA4/edit)", aquí está el detalle de la estructura del informe.
